// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact': string;
  'contacts': string;
  'info': string;
  'main': string;
  'quote': string;
  'resume': string;
  'resume_block': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
