// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flip_text': string;
  'main': string;
  'word': string;
}
export const cssExports: CssExports;
export default cssExports;
