// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'menu': string;
  'menu_item': string;
}
export const cssExports: CssExports;
export default cssExports;
