// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blog': string;
  'blog_header': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
